### ISSUE TITLE
fork error against windows server

### ISSUE THREAD

**Issue by dcb530** [dergachev/redmine_git_remote#33]
I am trying to using the plugin against Redmine 3.3 on Windows server. 

After I saved the setting of Clone URL for SSH, I got the Internal Error.  Checking the Redmine log, it shows as following:
`Started GET "/redmine/projects/testproject/repositories/new?repository_scm=GitRemote" for 127.0.0.1 at 2017-09-08 09:47:07 +0800
Processing by RepositoriesController#new as JS
  Parameters: {"repository_scm"=>"GitRemote", "project_id"=>"testproject"}
  Current user: daichengbo (id=8)
  Rendered repositories/_form.html.erb (2.0ms)
  Rendered repositories/new.html.erb (3.0ms)
  Rendered repositories/new.js.erb (4.0ms)
Completed 200 OK in 66ms (Views: 4.1ms | ActiveRecord: 56.0ms)
Started POST "/redmine/projects/testproject/repositories" for 127.0.0.1 at 2017-09-08 09:47:17 +0800
Processing by RepositoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"DypRYb/ojQHHhjesW1/JhkAnNmgMZvPYRHTFLk5zk99YxuZaeUADcqyKU94vUtL+DGRbJLpUUYhEtW/2eaQwmQ==", "repository_scm"=>"GitRemote", "repository"=>{"is_default"=>"0", "identifier"=>"", "url"=>"", "extra_clone_url"=>"git@GitLab.cdyoue.com:root/testproject.git"}, "commit"=>"创建", "project_id"=>"testproject"}
  Current user: daichengbo (id=8)
Completed 500 Internal Server Error in 104ms (ActiveRecord: 85.0ms)

NotImplementedError (fork() function is unimplemented on this machine):
  plugins/redmine_git_remote/lib/redmine_git_remote/poor_mans_capture3.rb:18:in `fork'
  plugins/redmine_git_remote/lib/redmine_git_remote/poor_mans_capture3.rb:18:in `capture3'
  plugins/redmine_git_remote/lib/redmine_git_remote/poor_mans_capture3.rb:38:in `capture2'
  plugins/redmine_git_remote/app/models/repository/git_remote.rb:160:in `add_known_host'
  plugins/redmine_git_remote/app/models/repository/git_remote.rb:94:in `ensure_possibly_empty_clone_exists'
  plugins/redmine_git_remote/app/models/repository/git_remote.rb:84:in `initialize_clone'
  app/controllers/repositories_controller.rb:55:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

**Comment by dcb530** [comment]
Here is my redmine info:

Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.2
  Filesystem                     
  GitRemote                      2.7.2
Redmine plugins:
  clipboard_image_paste          1.12
  plantuml                       0.3.0
  redmine_git_remote             0.0.1
  redmine_gitlab_hook            0.1.3
  redmine_ldap_sync              2.0.8.devel.g0ad6646785
  redmine_wiki_extensions        0.7.0
  sidebar_hide                   0.0.8
  status_button                  0.1.0

**Comment by dergachev** [comment]
It's not supported on Windows, unfortunately because I don't have a VM to test it.

But, some good people actually did a PR I didn't have a chance to test.

See #22 and the PR #23, and also the note at the end:
https://github.com/dergachev/redmine_git_remote/pull/23#issuecomment-320446136

Would love to hear your feedback, if you're capable of testing these changes.
