### ISSUE TITLE
Internal Server Error for SettingsController#index and AdminController#info

### ISSUE THREAD

**Issue by olafmandel** [dergachev/redmine_git_remote#42]
I cannot open the Administration->Settings nor the Administration->Information pages while this plugin is installed.

I use the official Redmine Docker image (https://hub.docker.com/_/redmine/), add the plugin (tag 0.0.2) via a bind-mount and the error starts happening directly after logging in for the first time.

Any suggestions? Thank you.

System information (without the plugin installed):

    Environment:
      Redmine version                3.4.6.stable
      Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
      Rails version                  4.2.8
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.9.5
      Mercurial                      4.0
      Bazaar                         2.8.0
      Git                            2.11.0
      Filesystem                     

It also fails the same way for a sqlite3 database.

Detailed error log:

    Started GET "/admin/info" for 10.0.1.4 at 2018-08-24 13:48:52 +0000
    Processing by AdminController#info as HTML
      Current user: admin (id=1)
      Rendered admin/info.html.erb within layouts/admin (180.1ms)
    Completed 500 Internal Server Error in 205ms (ActiveRecord: 7.5ms)
    
    ActionView::Template::Error (uninitialized constant Repository::GitRemote):
        12: </table>
        13: <br />
        14: <div class="box">
        15: <pre><%= Redmine::Info.environment %></pre>
        16: </div>
        17:
        18: <% html_title(l(:label_information_plural)) -%>
      lib/redmine/info.rb:21:in `block in environment'
      lib/redmine/info.rb:20:in `each'
      lib/redmine/info.rb:20:in `environment'
      app/views/admin/info.html.erb:15:in `_app_views_admin_info_html_erb___2626609327580126895_70130347473760'
      lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by olafmandel** [comment]
Found it: the plugin directory was not readable by the redmine-user.
